### ISSUE TITLE
Duplicación de mensajes a comandos

### ISSUE THREAD

**Issue by Beelzenef** [HonzoNebro/MiReinoBot#1]
Cuando se escribe cualquier comando, ya sea un /start o /XdY, se duplican los mensajes:

![imagen](https://user-images.githubusercontent.com/6389665/33263918-e7625056-d36b-11e7-820d-489b67b3bb42.png)

**Comment by HonzoNebro** [comment]
Me da que hay dos copias del bot funcionando, no le has cambiado el token (mea culpa incluirlo). Has de conseguir uno con el @botfather
